#if !canImport(ObjectiveC)
import XCTest

extension LeafKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LeafKitTests = [
        ("testLoader", testLoader),
        ("testNestedEcho", testNestedEcho),
        ("testParser", testParser),
        ("testParserasdf", testParserasdf),
    ]
}

extension LexerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LexerTests = [
        ("testConstant", testConstant),
        ("testEscaping", testEscaping),
        ("testNestedEcho", testNestedEcho),
        ("testParameters", testParameters),
        ("testParamNesting", testParamNesting),
        ("testTagIndicator", testTagIndicator),
        ("testTags", testTags),
    ]
}

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testCompileExtend", testCompileExtend),
        ("testCompiler2", testCompiler2),
        ("testCompiler", testCompiler),
        ("testComplex", testComplex),
        ("testDocumentResolveExtend", testDocumentResolveExtend),
        ("testInsertResolution", testInsertResolution),
        ("testNesting", testNesting),
        ("testParsingNesting", testParsingNesting),
        ("testPPP", testPPP),
        ("testShouldThrowCantResolve", testShouldThrowCantResolve),
    ]
}

extension PrintTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PrintTests = [
        ("testConditional", testConditional),
        ("testCustomTag", testCustomTag),
        ("testExtendAndExport", testExtendAndExport),
        ("testImport", testImport),
        ("testLoop", testLoop),
        ("testRaw", testRaw),
        ("testVariable", testVariable),
    ]
}

extension SerializerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SerializerTests = [
        ("testComplex", testComplex),
    ]
}

extension SomeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SomeTests = [
        ("testCodable", testCodable),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LeafKitTests.__allTests__LeafKitTests),
        testCase(LexerTests.__allTests__LexerTests),
        testCase(ParserTests.__allTests__ParserTests),
        testCase(PrintTests.__allTests__PrintTests),
        testCase(SerializerTests.__allTests__SerializerTests),
        testCase(SomeTests.__allTests__SomeTests),
    ]
}
#endif
